# Generated by Django 6.0 on 2025-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان لیست قیمت')),
                ('file', models.FileField(upload_to='pricelists/', verbose_name='فایل اصلی')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی تلگرام')),
                ('file_type', models.CharField(choices=[('photo', 'عکس'), ('document', 'سند')], default='document', max_length=20)),
                ('rank', models.IntegerField(default=0, verbose_name='رتبه نمایش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'لیست قیمت',
                'verbose_name_plural': 'لیست\u200cهای قیمت',
                'ordering': ['-rank', '-updated_at'],
            },
        ),
    ]
