# Generated by Django 6.0 on 2025-12-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_botuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-rank', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='file',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='telegram_file_id',
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان لیست'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PriceListFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pricelists/')),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('photo', 'عکس'), ('document', 'سند')], max_length=20)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prices.pricelist')),
            ],
        ),
    ]
