# Generated by Django 6.0 on 2025-12-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_pricelist_options_remove_pricelist_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistfile',
            name='file',
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricelistfile',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
    ]
