# Generated by Django 6.0 on 2025-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistfile',
            name='name',
            field=models.CharField(default='فایل شماره یک', max_length=255),
        ),
    ]
