# Generated by Django 6.0 on 2026-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_pricelistfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pricelistfile',
            name='bale_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pricelistfile',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
