# Generated by Django 6.0 on 2025-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('management', models.CharField(max_length=255, verbose_name='مدیریت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('landline', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن همراه')),
                ('activity', models.TextField(verbose_name='زمینه فعالیت')),
                ('rank', models.IntegerField(default=0, verbose_name='رتبه')),
                ('owner_telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='آیدی تلگرام مالک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
            ],
            options={
                'verbose_name': 'کسب و کار',
                'verbose_name_plural': 'کسب و کارها',
                'ordering': ['-rank', 'shop_name'],
            },
        ),
    ]
