# Generated by Django 6.0 on 2025-12-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='activity',
            field=models.TextField(blank=True, null=True, verbose_name='زمینه فعالیت'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='business',
            name='management',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدیریت'),
        ),
    ]
