# Generated by Django 6.0 on 2025-12-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_business_activity_alter_business_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='آیدی تلگرام متقاضی')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='یوزرنیم تلگرام')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید ادمین'), ('approved', 'تایید شده (کد ارسال شد)'), ('completed', 'مالکیت تایید شد')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.business', verbose_name='کسب و کار')),
            ],
            options={
                'verbose_name': 'درخواست ادعا',
                'verbose_name_plural': 'درخواست\u200cهای ادعا',
            },
        ),
    ]
