# Generated by Django 6.0 on 2025-12-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_claimrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterModelOptions(
            name='claimrequest',
            options={},
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.business'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
